### ISSUE TITLE
MAP/OSM : Add tile cache system

### ISSUE THREAD

**Issue by Th3NakedMan** [artmobilis/ArtMobilis-js#1]
In order to use less gps data transfer the app should embed the map of the artistic zone route (parcours artistique).

**Specification of the tile cache system (draft)**
- The tile cache will only be available around the artistic zone route.
- The tile cache should be easily changed for another artistic zone route
- ....

**Comment by d-j-a-y** [comment]
**TIPS**
- imgcache.js --> https://github.com/chrisben/imgcache.js/
- Zoomable image with Leaflet  : http://build-failed.blogspot.fr/2012/11/zoomable-image-with-leaflet.html
