### ISSUE TITLE
Libs : Update to Node.js 4.2.1 LTS

### ISSUE THREAD

**Issue by d-j-a-y** [artmobilis/ArtMobilis-js#18]
https://nodejs.org/en/blog/release/v4.2.1/

**Comment by ssm2017** [comment]
à tester mais il faudrait qu'on definisse les "minimum requirements" pour nos stations de dev comme reference et le noter dans le wiki : 

Linux : 
ubuntu version xxx
debian version xxx (je vais virer mon mint pour mettre debian 8)
(les autres distros à voir plus tard selon les devs futurs)

Windows : 
7.?
8.?
10.?

à la limite, la version de l'os on s'en fout car le plus important est la version des outils : 
node.js version xxx
ionic version xxx
cordova version xxx
android sdk version xxx
etc...

et qu'on s'y tienne en utilisant tous les memes versions pour le dev puis proposer des nouvelles versions au fil du temps et qu'on se mette à jour quand tout le monde est d'accord.

qu'en pensez vous ?

**Comment by ssm2017** [comment]
je suis en train de faire une procedure pour creer une machine de dev basée sur debian 8/gnome.
elle devrait etre compatible ubuntu.
je pars sur nodejs v4.2.1 et android sdk 24.4
voici le lien pour la procédure que je mettrai à jour par la suite avec ionic etc.. : 
http://wiki.ssm2017.com/node/75

**Comment by d-j-a-y** [comment]
> ssm2017 ... 

Ca me semle coherent.

En tenant compte des failles de secu" enventuelles des outils que nous utilisons... node.js par exemple, peut il etre generateur de faillles de secu ?

**Comment by ssm2017** [comment]
oui node peut etre sensible à des failles de sécu.
cependant, nous ne l'utilisons pas en tant que serveur web donc le probleme est limité et nous ne sommes pas sensibles aux risques de pénétration tant que nous n'hébergeons pas l'application en tant que service web.
cependant, si nous avons une installation corrompue, le fichier apk résultant de la compilation pourrait etre corrompu mais je n'ai pas entendu parler de probleme de ce coté pour le moment.

peut etre que nous devrions définir une station de compilation sûre qui pourrait servir pour toute compilation définitive des releases avant de les poster sur le store.

comme déjà indiqué, je suis en train de tenter de déterminer quels sont les outils et configurations nécéssaires à un bon developpement sous debian à prendre comme référence (voir : https://github.com/artmobilis/ArtMobilis-js/issues/21 ) et cette vm pourrait servir de base pour compiler seulement (pourquoi pas en faire une appliance par la suite ou un container docker qui pourraient etre hébergés mais d'abord la vm ce serait bien :) )
