### ISSUE TITLE
"A propos" page add more "debug" informations

### ISSUE THREAD

**Issue by Th3NakedMan** [artmobilis/ArtMobilis-js#2]
The "a propos" page could give more sensitive informations (useful for bug report)
- gps functionnaly / fixed by #10 
- connected / offline / fixed by #15 (do not work under linux & firefox41 !)
- os / browser name and version / fixed by #12
- Screen size / fixed by #12 
- javascript
- Platform #12

**Comment by d-j-a-y** [comment]
(done) os / browser name and version #12
(done) screen size #12 
(done) gps : https://github.com/artmobilis/ArtMobilis-js/pull/10

**Comment by d-j-a-y** [comment]
Je pens que je ne vais pas afficher l'info javascprit , si ont est la, c'est que deja le js fonctionne non ?
en revanche, un test plus amonts de js ... au moins que cela soit deja fait par cordova ? (ionic?)

Quelqu'un pense t'il a quelque chose qui manque a afficher pour le debug ?  (sinon , je fermerais l'issue)

**Comment by brucelane** [comment]
afficher le js n'est pas nécessaire...
je me demande si l'adresse ip est trouvable, mais c'est pas nécessaire non plus, juste par curiosité

**Comment by d-j-a-y** [comment]
TIPS : ionic Platform Classes - http://ionicframework.com/docs/platform-customization/platform-classes.html

**Comment by brucelane** [comment]
bonne trouvaille

**Comment by d-j-a-y** [comment]
> je me demande si l'adresse ip est trouvable,

Il semble que non pas vraiment possible sans faire appel a l'exterieur : http://stackoverflow.com/questions/391979/get-client-ip-using-just-javascript (pi etre le coup WebRTC /  answered Sep 29 at 10:03 mido22 / [exemple ici](https://github.com/diafygi/webrtc-ips) )
