### ISSUE TITLE
Séparer app et contenus spécifiques à un évènement

### ISSUE THREAD

**Issue by ssm2017** [artmobilis/ArtMobilis-js#49]
@brucelane 
@ssm2017

**Comment by brucelane** [comment]
je propose d'avoir un repo séparé pour les dossiers assets et img

**Comment by ssm2017** [comment]
- choisir une licence pour les contenus : http://creativecommons.fr/licences/#toc-les-licences-
- video proposée : https://archive.org/details/BigBuckBunnyProjectile1
- d'où sortent les contenus de "steven" ? (arcenciel-steven.gif et arciel-steven.mp3)
- photos de livres à remplacer
- revoir les modeles 3d car : 
  - pas centrés
  - meshes  à optimiser
